kind: Service
apiVersion: v1
metadata:
  name: hostname-service
spec:
  type: NodePort
  selector:
    app: sample-api
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sample-api
spec:
  containers:
    - name: sample-api
      image: sample-api-service:latest
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - "ALL"
          add: ["NET_ADMIN", "SYS_TIME"]